export const WORLD_CUP_FLAG_PATHS = {
  "algeria": "/worldcup-flags/algeria.png",
  "argentina": "/worldcup-flags/argentina.png",
  "australia": "/worldcup-flags/australia.png",
  "austria": "/worldcup-flags/austria.png",
  "belgium": "/worldcup-flags/belgium.png",
  "bosnia and herzegovina": "/worldcup-flags/bosnia-and-herzegovina.png",
  "brazil": "/worldcup-flags/brazil.png",
  "canada": "/worldcup-flags/canada.png",
  "cape verde": "/worldcup-flags/cape-verde.png",
  "colombia": "/worldcup-flags/colombia.png",
  "croatia": "/worldcup-flags/croatia.png",
  "curacao": "/worldcup-flags/curacao.png",
  "czech republic": "/worldcup-flags/czech-republic.png",
  "democratic republic of the congo": "/worldcup-flags/democratic-republic-of-the-congo.png",
  "ecuador": "/worldcup-flags/ecuador.png",
  "egypt": "/worldcup-flags/egypt.png",
  "england": "/worldcup-flags/england.png",
  "france": "/worldcup-flags/france.png",
  "germany": "/worldcup-flags/germany.png",
  "ghana": "/worldcup-flags/ghana.png",
  "haiti": "/worldcup-flags/haiti.png",
  "iran": "/worldcup-flags/iran.png",
  "iraq": "/worldcup-flags/iraq.png",
  "ivory coast": "/worldcup-flags/ivory-coast.png",
  "japan": "/worldcup-flags/japan.png",
  "jordan": "/worldcup-flags/jordan.png",
  "mexico": "/worldcup-flags/mexico.png",
  "morocco": "/worldcup-flags/morocco.png",
  "netherlands": "/worldcup-flags/netherlands.png",
  "new zealand": "/worldcup-flags/new-zealand.png",
  "norway": "/worldcup-flags/norway.png",
  "panama": "/worldcup-flags/panama.png",
  "paraguay": "/worldcup-flags/paraguay.png",
  "portugal": "/worldcup-flags/portugal.png",
  "qatar": "/worldcup-flags/qatar.png",
  "saudi arabia": "/worldcup-flags/saudi-arabia.png",
  "scotland": "/worldcup-flags/scotland.png",
  "senegal": "/worldcup-flags/senegal.png",
  "south africa": "/worldcup-flags/south-africa.png",
  "south korea": "/worldcup-flags/south-korea.png",
  "spain": "/worldcup-flags/spain.png",
  "sweden": "/worldcup-flags/sweden.png",
  "switzerland": "/worldcup-flags/switzerland.png",
  "tunisia": "/worldcup-flags/tunisia.png",
  "turkey": "/worldcup-flags/turkey.png",
  "united states": "/worldcup-flags/united-states.png",
  "uruguay": "/worldcup-flags/uruguay.png",
  "uzbekistan": "/worldcup-flags/uzbekistan.png"
}
